# URL kết nối JDBC
spring.datasource.url=jdbc:postgresql://localhost:5432/student_management
spring.datasource.username=postgres
spring.datasource.password=Vu@280605

# Cấu hình Hibernate (Tự động cập nhật bảng dựa trên Java class)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Tùy chọn: Hiển thị câu lệnh SQL trong console để debug
spring.jpa.show-sql=true
